services:
    - type: worker
    name: star-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
            - key: PYTHON_VERSION
        value: 3.11.9
            - key: BOT_TOKEN
        sync: false
            - key: MUSIC_API
        value: https://api.omegatech.app/api/ai/Remusicv2
            - key: LYRICS_API
        value: https://api.omegatech.app/api/ai/Gpt-4o-mini
